[
    {
        "title": "Google Pixel 4XL",
        "brand": "Google",
        "model": "Pixel 4XL",
        "price": ['230'],
        "salePrice": 230,
        "onStock": true,
        "color": ["Just Black","Clearly White","Orange"],
        "memory": ["64gb"],
        "img": ["https://dropshipping100.shop/cache/small/product/289/OmERyOIOfpXxwcw7f168v2Uu3cJfm9wmGoZR3l54.jpg"],
        "description": "",
        "discount": 0,
        "article": "ggl4xl",
        "simCard": 1,
    },
    {
        "title": "Google Pixel 4",
        "brand": "google",
        "model": "google4",
        "price": ['580'],
        "salePrice": 260,
        "onStock": true,
        "color": ["Just Black"],
        "memory": ["64gb"],
        "img": "https://content1.rozetka.com.ua/goods/images/big/109863438.jpg",
        "description": "",
        "discount": 0,
        "article": "google4",
        "simCard": 1,
    },
    {
        "title": "Google Pixel 4a",
        "brand": "google",
        "model": "google4a",
        "price": ['210'],
        "salePrice": 260,
        "onStock": true,
        "color": ["Just Black"],
        "memory": ["128Gb"],
        "img": "https://content.rozetka.com.ua/goods/images/big/9065931.jpg",
        "description": "",
        "discount": 0,
        "article": "google4a",
        "simCard": 1,
    },
    {
        "title": "Google Pixel 5",
        "brand": "google",
        "model": "google5",
        "price": ['250'],
        "salePrice": 260,
        "onStock": true,
        "color": ["Just Black"],
        "memory": ["128Gb"],
        "img": "https://content.rozetka.com.ua/goods/images/big/328421806.jpg",
        "description": "",
        "discount": 0,
        "article": "google5",
        "simCard": 1,
    },
    {
        "title": "Google Pixel 6",
        "brand": "google",
        "model": "google6",
        "price": ['390'],
        "salePrice": 260,
        "onStock": true,
        "color": ["Stormy Black"],
        "memory": ["128Gb"],
        "img": "https://content.rozetka.com.ua/goods/images/big/272741489.jpg",
        "description": "",
        "discount": 0,
        "article": "google6",
        "simCard": 1,
    },
    {
        "title": "Google Pixel 7a 8/128gb",
        "brand": "google",
        "model": "google7a",
        "price": ['410'],
        "salePrice": 260,
        "onStock": true,
        "color": ["Charcoal"],
        "memory": ["128Gb"],
        "img": "https://content.rozetka.com.ua/goods/images/big/272741489.jpg",
        "description": "",
        "discount": 0,
        "article": "google7a",
        "simCard": 1,
    },
    {
        "title": "Google Pixel 7 8/128gb",
        "brand": "google",
        "model": "google7",
        "price": ['460'],
        "salePrice": 260,
        "onStock": true,
        "color": ["Obsidian"],
        "memory": ["128Gb"],
        "img": "https://content.rozetka.com.ua/goods/images/big/272741489.jpg",
        "description": "",
        "discount": 0,
        "article": "google7",
        "simCard": 1,
    },
]

