[
    {
        "title": "Iphone SE 2020",
        "brand": "Apple",
        "model": "SE 2020",
        "price": ['235', '265'],
        "salePrice": 235,
        "onStock": true,
        "color": ["Black","White", "Red" ],
        "memory": ["64gb", "128gb"],
        "img": "https://dropshipping100.shop/cache/small/product/282/PApbe747bnWAXMEuYT89cXeUpkL7usCCUCKc2Tsl.png",
        "description": "",
        "discount": 0,
        "article": "aplse2020",
        "simCard": 1,
    },
    {
        "title": "Iphone SE 2022",
        "brand": "Apple",
        "model": "SE 2022",
        "price": ['430'],
        "salePrice": 430,
        "onStock": true,
        "color": ["Midnight","Starlight"],
        "memory": ["64gb"],
        "img": "https://dropshipping100.shop/cache/small/product/282/PApbe747bnWAXMEuYT89cXeUpkL7usCCUCKc2Tsl.png",
        "description": "",
        "discount": 0,
        "article": "aplse2022",
        "simCard": 1,
    },
    {
        "title": "Iphone 8 plus",
        "brand": "Apple",
        "model": "8 plus",
        "price": ['250', '310'],
        "salePrice": 250,
        "onStock": true,
        "color": ["Space Gray","Silver","Red","Gold"],
        "memory": ["64gb", '256gb'],
        "img": "https://dropshipping100.shop/cache/small/product/32/PVk3DZFiXeuYMt3jee2lRh6gxGT78V1lNO5ajya8.png",
        "description": "",
        "discount": 0,
        "article": "apl8pl",
        "simCard": 1,
    },
    {
        "title": "Iphone Xr",
        "brand": "Apple",
        "model": "Xr",
        "price": ['320', '360'],
        "salePrice": 320,
        "onStock": true,
        "color": ["Black","White","Red","Blue", "Coral", "Yellow"],
        "memory": ["64gb", '128gb'],
        "img": "https://dropshipping100.shop/cache/small/product/56/lW2fKprakN3XFM4GVOTQJ3bvfbKwtdvi61NIFeK2.png",
        "description": "",
        "discount": 0,
        "article": "aplxr",
        "simCard": 1,
    },
    {
        "title": "Iphone Xs",
        "brand": "Apple",
        "model": "Xs",
        "price": ['320', '360', '370'],
        "salePrice": 320,
        "onStock": true,
        "color": ["Space Gray","Silver","Gold"],
        "memory": ["64gb", '256gb', '512gb'],
        "img": "https://dropshipping100.shop/cache/small/product/44/rJRYsZjzlY5RRP9FFBVNU7CbJx4qbFc6nWxnO6Yz.png",
        "description": "",
        "discount": 0,
        "article": "aplxs",
        "simCard": 1,
    },
    {
        "title": "Iphone Xs Max",
        "brand": "Apple",
        "model": "Xs Max",
        "price": ['360', '430'],
        "salePrice": 360,
        "onStock": true,
        "color": ["Space Gray","Silver","Gold"],
        "memory": ["64gb", '512gb'],
        "img": "https://dropshipping100.shop/cache/small/product/51/gnhvsoj66EWRJyuMjCU8OqLnMcMdFlTlEUoQ59yg.png",
        "description": "",
        "discount": 0,
        "article": "aplxsmax",
        "simCard": 1,
    },
    {
        "title": "Iphone 11",
        "brand": "Apple",
        "model": "11",
        "price": ['410', '490', '510'],
        "salePrice": 410,
        "onStock": true,
        "color": ["Black","White","Purple", "Green","Red","Yellow"],
        "memory": ["64gb", '128gb', '256gb'],
        "img": "https://dropshipping100.shop/cache/small/product/75/ods3cvshDrYhMPV0E4MEyk18a831YlqkXweerwwc.png",
        "description": "",
        "discount": 0,
        "article": "apl11",
        "simCard": 1,
    },
    {
        "title": "Iphone 11 pro",
        "brand": "Apple",
        "model": "11 pro",
        "price": ['490', '570'],
        "salePrice": 490,
        "onStock": true,
        "color": ["Space Gray","Midnight Green","Silver", "Gold"],
        "memory": ["64gb", '256gb'],
        "img": "https://dropshipping100.shop/cache/small/product/82/kkxxZniYsRZsgbDkdTHfBNjdgHxQnCq4OXH6I4JL.png",
        "description": "",
        "discount": 0,
        "article": "apl11pro",
        "simCard": 1,
    },
    {
        "title": "Iphone 11 pro Max",
        "brand": "Apple",
        "model": "11 pro Max",
        "price": ['570', '650', '670'],
        "salePrice": 570,
        "onStock": true,
        "color": ["Space Gray","Midnight Green","Silver", "Gold"],
        "memory": ["64gb", '256gb', '512gb'],
        "img": "https://dropshipping100.shop/cache/small/product/94/baf1KFI3ptXyv0iqmCIq8PAdJ9P3RKzCwWi1ONY1.jpg",
        "description": "",
        "discount": 0,
        "article": "apl11promax",
        "simCard": 1,
    },
    {
        "title": "Iphone 12",
        "brand": "Apple",
        "model": "12",
        "price": ['530', '565'],
        "salePrice": 530,
        "onStock": true,
        "color": ["Black","White","Blue", "Green", "Purple","Red"],
        "memory": ["64gb", '128gb'],
        "img": "https://dropshipping100.shop/cache/small/product/103/TQWE76Z2i58cYdOUMQLXNXZ0tNS46GAip4HChOnn.webp",
        "description": "",
        "discount": 0,
        "article": "apl12",
        "simCard": 1,
    },
    {
        "title": "Iphone 13",
        "brand": "Apple",
        "model": "13",
        "price": ['780'],
        "salePrice": 780,
        "onStock": true,
        "color": ["Midnight","Starlight","Blue","Green"],
        "memory": ["256gb"],
        "img": ["https://dropshipping100.shop/cache/small/product/352/7iRmBJwq8Wc3IMHRDwP0v1X9n6Los43WkpmQeeKO.webp"],
        "description": "",
        "discount": 0,
        "article": "apl13",
        "simCard": 1,
    },
]

