[
    {
        "title": "LG V50",
        "brand": "lg",
        "model": "V50",
        "price": ['500'],
        "salePrice": 260,
        "onStock": true,
        "color": ["Black"],
        "memory": ["128gb"],
        "img": "https://content1.rozetka.com.ua/goods/images/big/261567669.jpg",
        "description": "",
        "discount": 0,
        "article": "lgv50",
        "simCard": 1,
    },
    {
        "title": "LG V50s",
        "brand": "lg",
        "model": "V50s",
        "price": ['180'],
        "salePrice": 260,
        "onStock": true,
        "color": ["Black"],
        "memory": ["256gb"],
        "img": "https://content1.rozetka.com.ua/goods/images/big/287689240.jpg",
        "description": "",
        "discount": 0,
        "article": "lgv50s",
        "simCard": 1,
    },
    {
        "title": "LG V60",
        "brand": "lg",
        "model": "V60",
        "price": ['190'],
        "salePrice": 260,
        "onStock": true,
        "color": ["Black"],
        "memory": ["128gb"],
        "img": "https://content1.rozetka.com.ua/goods/images/big/341275871.jpg",
        "description": "",
        "discount": 0,
        "article": "lgv60",
        "simCard": 1,
    },
    {
        "title": "LG G9 Velvet",
        "brand": "lg",
        "model": "G9",
        "price": ['255'],
        "salePrice": 260,
        "onStock": true,
        "color": ["Black"],
        "memory": ["128gb"],
        "img": "https://content1.rozetka.com.ua/goods/images/big/296742077.jpg",
        "description": "",
        "discount": 0,
        "article": "lgG9",
        "simCard": 1,
    },
    {
        "title": "LG Wing 5G 8/128Gb",
        "brand": "lg",
        "model": "wing5g",
        "price": ['210'],
        "salePrice": 260,
        "onStock": true,
        "color": ["Aurora Gray"],
        "memory": ["128gb"],
        "img": "https://content1.rozetka.com.ua/goods/images/big/328223602.jpg",
        "description": "",
        "discount": 0,
        "article": "lgWing5g",
        "simCard": 1,
    },
    {
        "title": "LG Wing DUOS 5G 8/128Gb",
        "brand": "lg",
        "model": "wing5gduos",
        "price": ['280'],
        "salePrice": 260,
        "onStock": true,
        "color": ["Aurora Gray"],
        "memory": ["128gb"],
        "img": "https://content1.rozetka.com.ua/goods/images/big/328223602.jpg",
        "description": "",
        "discount": 0,
        "article": "lgWing5gduos",
        "simCard": 1,
    },
]

