[
    {
        "title": "Xiaomi Redmi Note 10 Pro 8/256GB",
        "brand": "xiaomi",
        "model": "note10pro",
        "price": ['270'],
        "salePrice": 260,
        "onStock": true,
        "color": ["Onyx Gray"],
        "memory": ["256gb"],
        "img": "https://content.rozetka.com.ua/goods/images/big/310977132.jpg",
        "description": "",
        "discount": 0,
        "article": "xiaominote10pro",
        "simCard": 1,
    },
    {
        "title": "Xiaomi Redmi Note 11 Pro 5G 6/128gb",
        "brand": "xiaomi",
        "model": "note11pro",
        "price": ['260'],
        "salePrice": 260,
        "onStock": true,
        "color": ["Graphite Gray"],
        "memory": ["128gb"],
        "img": "https://content.rozetka.com.ua/goods/images/big/310977132.jpg",
        "description": "",
        "discount": 0,
        "article": "xiaominote11pro",
        "simCard": 1,
    },
    {
        "title": "Xiaomi Redmi Note 11S 5G 4/128Gb",
        "brand": "xiaomi",
        "model": "note11s",
        "price": ['260'],
        "salePrice": 260,
        "onStock": true,
        "color": ["Midnight Black"],
        "memory": ["128gb"],
        "img": "https://content.rozetka.com.ua/goods/images/big/310977132.jpg",
        "description": "",
        "discount": 0,
        "article": "xiaominote11s",
        "simCard": 1,
    },
    {
        "title": "Xiaomi 13 Lite 5G 8/256gb",
        "brand": "xiaomi",
        "model": "13lite",
        "price": ['260'],
        "salePrice": 260,
        "onStock": true,
        "color": ["Black"],
        "memory": ["256gb"],
        "img": "https://content.rozetka.com.ua/goods/images/big/327569069.jpg",
        "description": "",
        "discount": 0,
        "article": "xiaomi13lite",
        "simCard": 1,
    },

]

