[
    {
        "title": "Samsung Galaxy S9 ",
        "brand": "Samsung",
        "model": "S9",
        "price": ['210'],
        "salePrice": 210,
        "onStock": true,
        "color": ["black","Gray","Blue","Red","Purple"],
        "memory": ["64gb"],
        "img": ["https://dropshipping100.shop/cache/small/product/183/urkEnmAL9lkHqcYLprjkp92OXiiMcv0P2DGkAJlK.png"],
        "description": "",
        "discount": 0,
        "article": "SM-G960U",
        "simCard": 1,
    },
    {
        "title": "Samsung Galaxy S9 DUOS",
        "brand": "Samsung",
        "model": "S9 DUOS",
        "price": ['230'],
        "salePrice": 230,
        "onStock": true,
        "color": ["black","Gold","Gray","Blue","Red","Purple"],
        "memory": ["64gb"],
        "img": ["https://dropshipping100.shop/cache/small/product/180/GyYJYbVKAEDhSMWNWjFxxfWg9fnfD1Snf6XQmati.png"],
        "description": "",
        "discount": 0,
        "article": "SM-G960FD",
        "simCard": 2,
    },
    {
        "title": "Samsung Galaxy S9+",
        "brand": "Samsung",
        "model": "S9+",
        "price": ['230'],
        "salePrice": 230,
        "onStock": true,
        "color": ["black","Gold","Gray","Blue","Red","Purple"],
        "memory": ["64gb"],
        "img": ["https://dropshipping100.shop/cache/small/product/200/agxW2QRyNh7k7xg0GkCG8bddxgRZBU9rYAC9z7uS.png"],
        "description": "",
        "discount": 0,
        "article": "SM-G965U",
        "simCard": 1,
    },
    {
        "title": "Samsung Galaxy S9+ DUOS",
        "brand": "Samsung",
        "model": "S9+ DUOS",
        "price": ['270'],
        "salePrice": 270,
        "onStock": true,
        "color": ["black","Gold","Blue","Red","Purple"],
        "memory": ["64gb"],
        "img": ["https://dropshipping100.shop/cache/small/product/200/agxW2QRyNh7k7xg0GkCG8bddxgRZBU9rYAC9z7uS.png"],
        "description": "",
        "discount": 0,
        "article": "SM-G965FD",
        "simCard": 2,
    },
    {
        "title": "Samsung Galaxy S10e",
        "brand": "Samsung",
        "model": "S10e",
        "price": ['240'],
        "salePrice": 240,
        "onStock": true,
        "color": ["black","White","Green","Blue"],
        "memory": ["128gb"],
        "img": ["https://dropshipping100.shop/cache/small/product/234/dGqX9kXsdONyAIRbYWnitI8ZePYPDRClYFYMzyq6.png"],
        "description": "",
        "discount": 0,
        "article": "SM-G970U",
        "simCard": 1,
    },
    {
        "title": "Samsung Galaxy S10e DUOS",
        "brand": "Samsung",
        "model": "S10e DUOS",
        "price": ['290'],
        "salePrice": 290,
        "onStock": true,
        "color": ["black","White","Green","Blue"],
        "memory": ["128gb"],
        "img": ["https://dropshipping100.shop/cache/small/product/236/D2E9hohNFfjIhP1uveJiAO42LLdlQpw4Dtob9wMq.png"],
        "description": "",
        "discount": 0,
        "article": "SM-G970FD",
        "simCard": 2,
    },
    {
        "title": "Samsung Galaxy S10",
        "brand": "Samsung",
        "model": "S10",
        "price": ['280'],
        "salePrice": 280,
        "onStock": true,
        "color": ["black","White","Green","Blue"],
        "memory": ["128gb"],
        "img": ["https://dropshipping100.shop/cache/small/product/226/74Y6L36NKhH7roHEbjy9atxVdIDBMkWy2SoXrt6w.png"],
        "description": "",
        "discount": 0,
        "article": "SM-G973U",
        "simCard": 1,
    },
    {
        "title": "Samsung Galaxy S10 DUOS",
        "brand": "Samsung",
        "model": "S10 DUOS",
        "price": ['325'],
        "salePrice": 325,
        "onStock": true,
        "color": ["black","White","Green","Blue"],
        "memory": ["128gb"],
        "img": ["https://dropshipping100.shop/cache/small/product/224/PY3JL86jnLnYHqtx40LXP8cXVlmosumYDgsxEODd.png"],
        "description": "",
        "discount": 0,
        "article": "SM-G973FD",
        "simCard": 2,
    },
    {
        "title": "Samsung Galaxy S10+",
        "brand": "Samsung",
        "model": "S10+",
        "price": ['320'],
        "salePrice": 320,
        "onStock": true,
        "color": ["black","White","Green","Orange","Blue","Red"],
        "memory": ["128gb"],
        "img": ["https://dropshipping100.shop/cache/small/product/239/Iim0CMdHUVrUwXXLDDeid5raLUKEkoRQZinBhKNq.png"],
        "description": "",
        "discount": 0,
        "article": "SM-G975U",
        "simCard": 1,
    },
    {
        "title": "Samsung Galaxy S10+ DUOS",
        "brand": "Samsung",
        "model": "S10+ DUOS",
        "price": ['350'],
        "salePrice": 350,
        "onStock": true,
        "color": ["black","White","Green","Blue"],
        "memory": ["128gb"],
        "img": ["https://dropshipping100.shop/cache/small/product/238/xizyqkTIpgsSICRiefzWwgVQxSancUX0plj6maQQ.png"],
        "description": "",
        "discount": 0,
        "article": "SM-G975FD",
        "simCard": 2,
    },
    {
        "title": "Samsung Galaxy S20 5G",
        "brand": "Samsung",
        "model": "S20",
        "price": ['390'],
        "salePrice": 390,
        "onStock": true,
        "color": ["black", "Gray", "White","Blue"],
        "memory": ["128gb"],
        "img": ["https://dropshipping100.shop/cache/small/product/300/p9VAIaoLuEakE0I6SB3HMvtNHlrsqv7mcI2IR4am.png"],
        "description": "",
        "discount": 0,
        "article": "SM-G981U",
        "simCard": 1,
    },
    {
        "title": "Samsung Galaxy S20 DUOS 5G",
        "brand": "Samsung",
        "model": "S20 DUOS",
        "price": ['430'],
        "salePrice": 430,
        "onStock": true,
        "color": ["black", "Gray", "White","Blue", "Pink"],
        "memory": ["128gb"],
        "img": ["https://dropshipping100.shop/cache/small/product/299/kgwvkkHgxM259gTobet2rR6TqET90iyYijjkg4DC.png"],
        "description": "",
        "discount": 0,
        "article": "SM-G981B/DS",
        "simCard": 2,
    },
]

