[
    {
        "title": "Xiaomi Redmi Note 10 Pro 8/256",
        "brand": "Xiaomi",
        "model": "Redmi Note 10 Pro",
        "price": ['260'],
        "salePrice": 260,
        "onStock": true,
        "color": ["Onyx Gray","Nebula Purple", "Glacier Blue", "Gradient Bronze", "Aurora Green" ],
        "memory": ["256gb"],
        "img": "",
        "description": "",
        "discount": 0,
        "article": "xiarn10pro",
        "simCard": 2,
    },
    {
        "title": "Xiaomi Redmi Note 11 Pro 6/128",
        "brand": "Xiaomi",
        "model": "Redmi Note 11 Pro",
        "price": ['260'],
        "salePrice": 260,
        "onStock": true,
        "color": ["Graphite Gray" ],
        "memory": ["128gb"],
        "img": "",
        "description": "",
        "discount": 0,
        "article": "xiarn11pro",
        "simCard": 2,
    },
    {
        "title": "Xiaomi Redmi Note 11s 4/128",
        "brand": "Xiaomi",
        "model": "Redmi Note 11s",
        "price": ['210'],
        "salePrice": 210,
        "onStock": true,
        "color": ["Midnight Black" ],
        "memory": ["128gb"],
        "img": "",
        "description": "",
        "discount": 0,
        "article": "xiarn11s",
        "simCard": 2,
    },
    
]

